# Generated by Django 5.0.6 on 2024-06-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Cantperson', models.PositiveIntegerField()),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Descripcion', models.TextField()),
                ('Disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
