# Generated by Django 5.0.6 on 2024-07-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('CALIENTE', 'Bebida Caliente'), ('FRIA', 'Bebida Fría')], default='CALIENTE', max_length=10),
        ),
    ]
