# Generated by Django 5.0.6 on 2024-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0002_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_Nombre', models.CharField(max_length=30)),
                ('Segundo_Nombre', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Cumpleaños', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
