# Generated by Django 5.0.6 on 2024-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0005_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'gramos'), ('kg', 'kilogramos'), ('l', 'litros'), ('ml', 'mililitros')], default='g', max_length=10),
        ),
    ]
