# Generated by Django 5.0.6 on 2024-06-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0009_remove_venta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_en_stock',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'gramos'), ('kg', 'kilogramos'), ('l', 'litros'), ('ml', 'mililitros')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='myappcafe.producto'),
        ),
    ]
