# Generated by Django 5.0.6 on 2024-06-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0012_producto_requiere_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_en_stock',
            field=models.IntegerField(default=0),
        ),
    ]
