# Generated by Django 5.0.6 on 2024-06-22 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0014_remove_venta_cantidad_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myappcafe.producto'),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
