# Generated by Django 5.0.6 on 2024-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0020_rename_hora_fin_reserva_fecha_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
