# Generated by Django 5.0.6 on 2024-06-25 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0021_alter_reserva_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('G', 'gramos'), ('MG', 'miligramos')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcafe.customuser')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcafe.venta')),
            ],
        ),
    ]
