# Generated by Django 5.0.6 on 2024-06-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0022_ingrediente_unidad_medida_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('G', 'gramos'), ('MG', 'miligramos')], default='G', max_length=2),
        ),
    ]
