# Generated by Django 5.0.6 on 2024-06-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0024_boleta_reserva_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('productos', models.ManyToManyField(related_name='menus', to='myappcafe.producto')),
            ],
        ),
    ]
