# Generated by Django 5.0.6 on 2024-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcafe', '0027_contactmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
